// <auto-generated />
using System;
using Genilog_WebApi.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Genilog_WebApi.Migrations
{
    [DbContext(typeof(Genilog_Data_Context))]
    [Migration("20250116104413_InitFistData")]
    partial class InitFistData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Genilog_WebApi.Model.AdminsModel.AdminModelTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatePublished")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminModelTables");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.DeviceTokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceTokenModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.GeneralUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("LockOutEndEnabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PhoneNoConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PhoneNoTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GeneralUsers");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.User_Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GeneralUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GeneralUsersId");

                    b.HasIndex("RoleId");

                    b.ToTable("User_Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.InfoModel.FeedbackModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatePublished")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeedbackModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.CompanyModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyRegNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("NoOfTrucks")
                        .HasColumnType("int");

                    b.Property<int>("NofOfBikes")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValueCharge")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CompanyModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.CompanyReviewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyModelDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingNum")
                        .HasColumnType("float");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyModelDataId");

                    b.ToTable("CompanyReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.OrderModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CurrentLongitude")
                        .HasColumnType("float");

                    b.Property<string>("ExpectedDeliveryTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ItemCost")
                        .HasColumnType("float");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("LogisticsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RecieverLatitude")
                        .HasColumnType("float");

                    b.Property<string>("RecieverLocality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RecieverLongitude")
                        .HasColumnType("float");

                    b.Property<string>("RecieverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SenderLatitude")
                        .HasColumnType("float");

                    b.Property<string>("SenderLocality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SenderLongitude")
                        .HasColumnType("float");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ShippingCost")
                        .HasColumnType("float");

                    b.Property<string>("TrackingNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrnxReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("OrderModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersChatModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupChatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RidersChatModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RidersModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersReviewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingNum")
                        .HasColumnType("float");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RidersModelDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RidersModelDataId");

                    b.ToTable("RidersReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.Notification_Model.NotificationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("NotificationModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationChatModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupChatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("ItemImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AccomodationChatModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<double>("BookingAmount")
                        .HasColumnType("float");

                    b.Property<string>("CheckInTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckOutTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccomodationAdvertType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("NoOfRooms")
                        .HasColumnType("int");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationFacilities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Facilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AccomodationDataTableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataTableId");

                    b.ToTable("AccomodationFacilities");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationFridayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationFriday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataTableId");

                    b.ToTable("AccomodationImages");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationMondayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationMonday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationReviewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AccomodationDataTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingNum")
                        .HasColumnType("float");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataTableId");

                    b.ToTable("AccomodationReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationSaturdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationSaturday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationSundayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationSunday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationThursdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationThursday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationTuesdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationTuesday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationWednesdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationWednesday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirCraftList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Facilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId");

                    b.ToTable("AirCraftList");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirlineImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId");

                    b.ToTable("AirlineImages");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirlineReviewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingNum")
                        .HasColumnType("float");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId");

                    b.ToTable("AirlineReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirlinePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId");

                    b.ToTable("AirlinePayments");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirlineChatModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupChatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AirlineChatModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<double>("BookingAmount")
                        .HasColumnType("float");

                    b.Property<string>("AirlinePhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckInTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckOutTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPayment")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PlaceAdvertType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacePhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacesHighlights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesFridayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId")
                        .IsUnique();

                    b.ToTable("PlaceFriday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesMondayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId")
                        .IsUnique();

                    b.ToTable("PlaceMonday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesSaturdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId")
                        .IsUnique();

                    b.ToTable("PlaceSaturday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesSundayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId")
                        .IsUnique();

                    b.ToTable("PlaceSunday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesThursdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId")
                        .IsUnique();

                    b.ToTable("PlaceThursday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesTuesdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId")
                        .IsUnique();

                    b.ToTable("PlaceTuesday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesWednesdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId")
                        .IsUnique();

                    b.ToTable("PlaceWednesday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.UsersDataModel.DeliveryAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressPostCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsersDataModelTableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsersDataModelTableId");

                    b.ToTable("DeliveryAddresses");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.UsersDataModel.UsersDataModelTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UsersDataModelTables");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.WalletModel.PayoutDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PayOutDateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PayOutStatus")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PayoutDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.User_Role", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.AuthModel.GeneralUsers", "GeneralUsers")
                        .WithMany("User_Roles")
                        .HasForeignKey("GeneralUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Genilog_WebApi.Model.AuthModel.Roles", "Roles")
                        .WithMany("User_Roles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralUsers");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.CompanyReviewModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.LogisticsModel.CompanyModelData", "CompanyModelDatas")
                        .WithMany("CompanyReviewModels")
                        .HasForeignKey("CompanyModelDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersReviewModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.LogisticsModel.RidersModelData", "RidersModelDatas")
                        .WithMany("RidersReviewModels")
                        .HasForeignKey("RidersModelDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RidersModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationFacilities", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataTables")
                        .WithMany("AccomodationFacilities")
                        .HasForeignKey("AccomodationDataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataTables");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationFridayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationFriday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.AccomodationFridayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationImages", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataTables")
                        .WithMany("AccomodationImages")
                        .HasForeignKey("AccomodationDataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataTables");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationMondayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationMonday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.AccomodationMondayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationReviewModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataTables")
                        .WithMany("AccomodationReviewModels")
                        .HasForeignKey("AccomodationDataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataTables");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationSaturdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationSaturday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.AccomodationSaturdayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationSundayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationSunday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.AccomodationSundayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationThursdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationThursday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.AccomodationThursdayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationTuesdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationTuesday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.AccomodationTuesdayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationWednesdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationWednesday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.AccomodationWednesdayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirCraftList", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithMany("AirCraftList")
                        .HasForeignKey("AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirlineImages", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithMany("AirlineImages")
                        .HasForeignKey("AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirlineReviewModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithMany("AirlineReviewModels")
                        .HasForeignKey("AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirlinePayment", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithMany("AirlinePayments")
                        .HasForeignKey("AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesFridayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithOne("PlacesFriday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.PlacesFridayModel", "AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesMondayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithOne("PlacesMonday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.PlacesMondayModel", "AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesSaturdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithOne("PlacesSaturday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.PlacesSaturdayModel", "AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesSundayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithOne("PlacesSunday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.PlacesSundayModel", "AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesThursdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithOne("PlacesThursday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.PlacesThursdayModel", "AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesTuesdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithOne("PlacesTuesday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.PlacesTuesdayModel", "AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.PlacesWednesdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", "AirlineDataModels")
                        .WithOne("PlacesWednesday")
                        .HasForeignKey("Genilog_WebApi.Model.PlacesModel.PlacesWednesdayModel", "AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.UsersDataModel.DeliveryAddress", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.UsersDataModel.UsersDataModelTable", "UsersDataModelTable")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("UsersDataModelTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsersDataModelTable");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.GeneralUsers", b =>
                {
                    b.Navigation("User_Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.Roles", b =>
                {
                    b.Navigation("User_Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.CompanyModelData", b =>
                {
                    b.Navigation("CompanyReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersModelData", b =>
                {
                    b.Navigation("RidersReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AccomodationDataModel", b =>
                {
                    b.Navigation("AccomodationFacilities");

                    b.Navigation("AccomodationFriday");

                    b.Navigation("AccomodationImages");

                    b.Navigation("AccomodationMonday");

                    b.Navigation("AccomodationReviewModels");

                    b.Navigation("AccomodationSaturday");

                    b.Navigation("AccomodationSunday");

                    b.Navigation("AccomodationThursday");

                    b.Navigation("AccomodationTuesday");

                    b.Navigation("AccomodationWednesday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.PlacesModel.AirlineDataModel", b =>
                {
                    b.Navigation("AirCraftList");

                    b.Navigation("AirlineImages");

                    b.Navigation("AirlineReviewModels");

                    b.Navigation("AirlinePayments");

                    b.Navigation("PlacesFriday");

                    b.Navigation("PlacesMonday");

                    b.Navigation("PlacesSaturday");

                    b.Navigation("PlacesSunday");

                    b.Navigation("PlacesThursday");

                    b.Navigation("PlacesTuesday");

                    b.Navigation("PlacesWednesday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.UsersDataModel.UsersDataModelTable", b =>
                {
                    b.Navigation("DeliveryAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
