// <auto-generated />
using System;
using Genilog_WebApi.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Genilog_WebApi.Migrations
{
    [DbContext(typeof(Genilog_Data_Context))]
    partial class Genilog_Data_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Genilog_WebApi.Model.AdminsModel.AdminModelTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CompanyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatePublished")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminModelTables");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AdminsModel.AdvertHolderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdvertDays4")
                        .HasColumnType("int");

                    b.Property<string>("AdvertImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AdvertItemCost")
                        .HasColumnType("float");

                    b.Property<string>("AdvertItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AdvertItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdvertName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdvertType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AdvertHolderModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AdminsModel.CompanyApplyDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CompanyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyApplyDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.DeviceTokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceTokenModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.GeneralUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LockOutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("LockOutEndEnabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PhoneNoConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PhoneNoTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GeneralUsers");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.User_Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GeneralUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GeneralUsersId");

                    b.HasIndex("RoleId");

                    b.ToTable("User_Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationChatModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupChatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("ItemImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AccomodationChatModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccomodationAdvertType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationEmail")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AccomodationFacilities")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AccomodationImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<double>("BookingAmount")
                        .HasColumnType("float");

                    b.Property<string>("CheckInTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckOutTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("NoOfRooms")
                        .HasColumnType("int");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationFridayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationFriday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationMondayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationMonday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationReviewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingNum")
                        .HasColumnType("float");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataTableId");

                    b.ToTable("AccomodationReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationSaturdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationSaturday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationSundayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationSunday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationThursdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationThursday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationTuesdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationTuesday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationWednesdayModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HourEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HourStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationDataModelId")
                        .IsUnique();

                    b.ToTable("AccomodationWednesday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AirCraftList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId");

                    b.ToTable("AirCraftList");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AirLineServiceLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId");

                    b.ToTable("AirLineServiceLocations");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AirlineChatModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupChatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AirlineChatModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AirlineDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AirlineEmail")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AirlineImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlinePhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<double>("BookingAmount")
                        .HasColumnType("float");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AirlineReviewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirlineDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingNum")
                        .HasColumnType("float");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineDataModelId");

                    b.ToTable("AirlineReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.BookAccomodationReservatioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccomodationImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationLocality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<int?>("MaximumNoOfGuest")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("RoomFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("RoomImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<double>("RoomPrice")
                        .HasColumnType("float");

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateddAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BookAccomodationReservatioModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.CustomerBookedReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccomodationImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("PaymentChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResevationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<bool>("TicketClosed")
                        .HasColumnType("bit");

                    b.Property<string>("TicketNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalCost")
                        .HasColumnType("float");

                    b.Property<string>("TrnxReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateddAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CustomerBookedReservations");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.FlightTicketBookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AirlineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvailabeTimeInterval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Available")
                        .HasColumnType("bit");

                    b.Property<int?>("BigLuggageKg")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dapature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapatureTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureAirpot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsReturn")
                        .HasColumnType("bit");

                    b.Property<string>("OperatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnAirpot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SmallLuggageKg")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("StopPlaces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stops")
                        .HasColumnType("int");

                    b.Property<string>("TicketNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TicketPrice")
                        .HasColumnType("float");

                    b.Property<string>("TicketType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FlightTicketBookModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.InfoModel.FeedbackModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatePublished")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeedbackModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.CompanyModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyRegNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("DeliveryTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("NoOfTrucks")
                        .HasColumnType("int");

                    b.Property<int>("NofOfBikes")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ServiceAreas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValueCharge")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CompanyModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.CompanyReviewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyModelDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingNum")
                        .HasColumnType("float");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyModelDataId");

                    b.ToTable("CompanyReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.OrderDeliveryFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CurrentLatitude")
                        .HasColumnType("float");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrentLongitude")
                        .HasColumnType("float");

                    b.Property<Guid>("OrderModelDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderModelDataId");

                    b.ToTable("OrderDeliveryFlows");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.OrderModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentLatitude")
                        .HasColumnType("float");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrentLongitude")
                        .HasColumnType("float");

                    b.Property<string>("ExpectedDeliveryTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ItemCost")
                        .HasColumnType("float");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemModelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<double>("ItemWeight")
                        .HasColumnType("float");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PackageImageLists")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RecieverLatitude")
                        .HasColumnType("float");

                    b.Property<string>("RecieverLocality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RecieverLongitude")
                        .HasColumnType("float");

                    b.Property<string>("RecieverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecieverState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SenderLatitude")
                        .HasColumnType("float");

                    b.Property<string>("SenderLocality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SenderLongitude")
                        .HasColumnType("float");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ShippingCost")
                        .HasColumnType("float");

                    b.Property<string>("ShippingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrnxReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("VatCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OrderModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersChatModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupChatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RidersChatModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersModelData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RidersModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersReviewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingNum")
                        .HasColumnType("float");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RidersModelDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RidersModelDataId");

                    b.ToTable("RidersReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.Notification_Model.NotificationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("NotificationModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.UsersDataModel.DeliveryAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressPostCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HouseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsersDataModelTableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsersDataModelTableId");

                    b.ToTable("DeliveryAddresses");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.UsersDataModel.UsersDataModelTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("MoneyBoxBalance")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UsersDataModelTables");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.WalletModel.TransactionDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrnxRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrnxStatus")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TransactionDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.User_Role", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.AuthModel.GeneralUsers", "GeneralUsers")
                        .WithMany("User_Roles")
                        .HasForeignKey("GeneralUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Genilog_WebApi.Model.AuthModel.Roles", "Roles")
                        .WithMany("User_Roles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralUsers");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationFridayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationFriday")
                        .HasForeignKey("Genilog_WebApi.Model.BookingsModel.AccomodationFridayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationMondayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationMonday")
                        .HasForeignKey("Genilog_WebApi.Model.BookingsModel.AccomodationMondayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationReviewModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", "AccomodationDataTables")
                        .WithMany("AccomodationReviewModels")
                        .HasForeignKey("AccomodationDataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataTables");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationSaturdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationSaturday")
                        .HasForeignKey("Genilog_WebApi.Model.BookingsModel.AccomodationSaturdayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationSundayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationSunday")
                        .HasForeignKey("Genilog_WebApi.Model.BookingsModel.AccomodationSundayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationThursdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationThursday")
                        .HasForeignKey("Genilog_WebApi.Model.BookingsModel.AccomodationThursdayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationTuesdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationTuesday")
                        .HasForeignKey("Genilog_WebApi.Model.BookingsModel.AccomodationTuesdayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationWednesdayModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", "AccomodationDataModels")
                        .WithOne("AccomodationWednesday")
                        .HasForeignKey("Genilog_WebApi.Model.BookingsModel.AccomodationWednesdayModel", "AccomodationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccomodationDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AirCraftList", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AirlineDataModel", "AirlineDataModels")
                        .WithMany("AirCraftList")
                        .HasForeignKey("AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AirLineServiceLocation", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AirlineDataModel", "AirlineDataModels")
                        .WithMany("AirLineServiceLocations")
                        .HasForeignKey("AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AirlineReviewModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.BookingsModel.AirlineDataModel", "AirlineDataModels")
                        .WithMany("AirlineReviewModels")
                        .HasForeignKey("AirlineDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirlineDataModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.CompanyReviewModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.LogisticsModel.CompanyModelData", "CompanyModelDatas")
                        .WithMany("CompanyReviewModels")
                        .HasForeignKey("CompanyModelDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.OrderDeliveryFlow", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.LogisticsModel.OrderModelData", "OrderModelDatas")
                        .WithMany("OrderDeliveryFlows")
                        .HasForeignKey("OrderModelDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersReviewModel", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.LogisticsModel.RidersModelData", "RidersModelDatas")
                        .WithMany("RidersReviewModels")
                        .HasForeignKey("RidersModelDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RidersModelDatas");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.UsersDataModel.DeliveryAddress", b =>
                {
                    b.HasOne("Genilog_WebApi.Model.UsersDataModel.UsersDataModelTable", "UsersDataModelTable")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("UsersDataModelTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsersDataModelTable");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.GeneralUsers", b =>
                {
                    b.Navigation("User_Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.AuthModel.Roles", b =>
                {
                    b.Navigation("User_Roles");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AccomodationDataModel", b =>
                {
                    b.Navigation("AccomodationFriday");

                    b.Navigation("AccomodationMonday");

                    b.Navigation("AccomodationReviewModels");

                    b.Navigation("AccomodationSaturday");

                    b.Navigation("AccomodationSunday");

                    b.Navigation("AccomodationThursday");

                    b.Navigation("AccomodationTuesday");

                    b.Navigation("AccomodationWednesday");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.BookingsModel.AirlineDataModel", b =>
                {
                    b.Navigation("AirCraftList");

                    b.Navigation("AirLineServiceLocations");

                    b.Navigation("AirlineReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.CompanyModelData", b =>
                {
                    b.Navigation("CompanyReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.OrderModelData", b =>
                {
                    b.Navigation("OrderDeliveryFlows");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.LogisticsModel.RidersModelData", b =>
                {
                    b.Navigation("RidersReviewModels");
                });

            modelBuilder.Entity("Genilog_WebApi.Model.UsersDataModel.UsersDataModelTable", b =>
                {
                    b.Navigation("DeliveryAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
